services:
  postgres:
    image: postgres:17-alpine3.19
    container_name: ol-test-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./OL-TechnicalTest-Backend
      dockerfile: Dockerfile
    container_name: ol-test-nest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local